Client:
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDITCCAgmgAwIBAgIRAKVUNVlVVE/wwla83R/ZQK4wDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTE4MDgwNjEyMzAwNVoXDTE5
    MDgwNjEyMzAwNVowGjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMIIBIjANBgkq
    hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxfBCvPQ4KxlmtXvOzoO6KMgiOGRsFDZh
    Oz574jOe4ZIw9YfE3FM8vxCsIwiC3A60cP/FnVSMwZAltkvfd+AfVQqeWeOq02uJ
    5JGWx56AUmrvJllar36Ai2LEeSfoBqmWY5uI/e+ElAxnwsBO46CyL1MA4RpNHTCE
    wc5Ubp312SFlrQdi3KscLeav5l60bVXphoSAzGelrPs4/DebG/aD5SbDm3qc/cf9
    iGmhZEtCCU1loUEOifAWyhHCyQYVXIJATWxP+6jX2ASkKtZ+iyNMGoMjVIF4t6tD
    IRDLNiekYPdXLkl+5L5bMANvTBwzbHuDtPx6wgPd5DtKXD8KEzSRgQIDAQABo2Iw
    YDAOBgNVHQ8BAf8EBAMCAqQwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDwYDVR0TAQH/
    BAUwAwEB/zAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNv
    bTANBgkqhkiG9w0BAQsFAAOCAQEAf9T8OjnPzgb23lHJqCJ+TQoSk/ztoih3KJ6d
    4jGEC1mZAhU/v2Jkxqc+Gq2J+sG9mKpUfk0KEw3fEUB4sAfTbnh0mtcIu/foKOM+
    Vj0EKQ5tCKpjq+G7lOFlPd5QzqxVW9AOVSnrvj/GZYLt+RfXVFxXijgyriLNniFi
    t1kjZIYxVPoPwS9W7fJKjgNLtSWOX/iEp4RUQr5E+YgFJkDcIMwuJJOOOjbUpAtp
    CvhAfUMmZZ19wtN+37GflrcjDw7VzerTqNJ3gx6iF7Xy7AebkzvEjuyy7d7xKGdM
    Dixe4BWrhpv6DhOBWvtc/gpeqQP+EA71GuAZdQQC6NFdfXekBQ==
    -----END CERTIFICATE-----
  max_poll: 600
  nonce: ukqqtSpJNUw=
  server_urls:
  - http://localhost:8000/
  windows_installer:
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_name: Velociraptor
  writeback_linux: /tmp/velociraptor.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
version:
  build_time: "2018-08-28T16:06:59+10:00"
  commit: 0c145ac342cbb0f510ac90d59d5ea3edf7e8fca2
  name: velociraptor
  version: 0.2.2
